### ISSUE TITLE
Meaning of "in_memory_percentage" config parameter

### ISSUE THREAD

**Issue by KDuzinkiewicz** [drethage/speech-denoising-wavenet#29]
The config file documentation mentions that:
"...in_memory_percentage: (float) Percentage of the dataset to load into memory, useful when dataset requires more memory than available..."

Does it mean that if I set the value to "1.00" the training toolchain will try load 100% of the recordings to memory? 
And when I set it to "0.10" the training toolchain will try load only 10% of the recordings to memory at first, but later it will eventually load the other 90% during subsequent iterations - or it will just use 10% in total and ignore the other 90%?

**Comment by MeiGM** [comment]
How did you train this model, I follow the author's code, the following error will occur
Using Theano backend.
E:\anaconda\lib\site-packages\theano\gpuarray\dnn.py:184: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to a version >= v5 and <= v7.
  warnings.warn("Your cuDNN version is more recent than "
Using cuDNN version 7401 on context None
Mapped name None to device cuda: GeForce GTX 1060 (0000:01:00.0)
Traceback (most recent call last):
  File "main.py", line 169, in <module>
    main()
  File "main.py", line 165, in main
    inference(config, cla)
  File "main.py", line 108, in inference
    load_checkpoint=cla.load_checkpoint, print_model_summary=cla.print_model_summary)
  File "E:\speech-denoising-wavenet-master\models.py", line 67, in __init__
    self.model = self.setup_model(load_checkpoint, print_model_summary)
  File "E:\speech-denoising-wavenet-master\models.py", line 76, in setup_model
    model = self.build_model()
  File "E:\speech-denoising-wavenet-master\models.py", line 220, in build_model
    name='data_input_target_field_length')(data_expanded)
  File "E:\anaconda\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "E:\speech-denoising-wavenet-master\layers.py", line 47, in call
    x = keras.backend.permute_dimensions(x, [0, 2, 1])
  File "E:\anaconda\lib\site-packages\keras\backend\theano_backend.py", line 936, in permute_dimensions
    y._keras_shape = tuple(np.asarray(x._keras_shape)[list(pattern)])
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by KDuzinkiewicz** [comment]
Hi,
   I followed the instructions on the GitHub and didn't run into same issue
as you, sorry :(

Regards

Karol

śr., 13 mar 2019, 08:53 użytkownik 梦想好 <notifications@github.com> napisał:
