### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by GrahamboJangles** [drethage/speech-denoising-wavenet#34]
Windows 10, python 3.6.3

Full error when trying to run main.py:

     Using TensorFlow backend.
     Traceback (most recent call last):
       File "\speech-denoising-wavenet-master\main.py", line 169, in <module>
         main()
       File "speech-denoising-wavenet-master\main.py", line 163, in main
         training(config, cla)
       File "\speech-denoising-wavenet-master\main.py", line 72, in training
         model = models.DenoisingWavenet(config, load_checkpoint=cla.load_checkpoint, print_model_summary=cla.print_model_summary)
       File "speech-denoising-wavenet-master\models.py", line 50, in __init__
         self.samples_of_interest_indices = self.get_padded_target_field_indices()
       File "speech-denoising-wavenet-master\models.py", line 184, in get_padded_target_field_indices
         target_sample_index + self.half_target_field_length + self.target_padding + 1)
     TypeError: 'float' object cannot be interpreted as an integer

**Comment by pkrysenko** [comment]
It causes, because you use python3, this project uses python2

**Comment by huihui890** [comment]
I have encountered the same problem, but python2.7 does not support GPU on windows. Have you solved this problem?

**Comment by GrahamboJangles** [comment]
> I have encountered the same problem, but python2.7 does not support GPU on windows. Have you solved this problem?

No, @huihui890 unfortunately not. [This](https://github.com/mosheman5/DNP) is, I believe, the only one I got at least running on my computer but I created another issue on there because it was taking a ridiculous amount of time to run. Good look, and if you find a repository that does allow you to train and denoise your audio files link me to it because I would like to use it as well!

**Comment by GrahamboJangles** [comment]
@huihui890 I now use Google Colab for many of my neural network needs and it seems to work better. I would recommend you give this repository a try with Google Colab. I might link a notebook here if I can get it working.

**Comment by huihui890** [comment]
@GrahamboJangles  Thank you very much for your recommendation, I will go to run Google Colab model as soon as possible.

**Comment by GrahamboJangles** [comment]
@huihui890 I started one [here](https://colab.research.google.com/drive/1U2AuGPqqGIMy1yGhEkaB3XJI4botmcYu?authuser=1#scrollTo=XyBsB9j6EwL8) but couldn't quite get it working. I get [this error](https://github.com/drethage/speech-denoising-wavenet/issues/37).

**Comment by huihui890** [comment]
@GrahamboJangles I will go to run this model as soon as possible.
